# Disparidade de Gênero no Setor da Tecnologia


**Pedro Lansdowne Oliveira, pedro.lansdowne@sga.pucminas.br**

**Leonardo Andrade Caetano Dornelas, lacdornelas@sga.pucminas.br**

**Augusto Henrique Gonçalves Valbonetti, ahgvalbonetti@sga.pucminas.br**

**Eduardo Fraga Fonseca Gomes, eduardo.fonseca@sga.pucminas.br**

**Vitor Martins Gonçalves, vitor.goncalves@sga.pucminas.br**

**Gustavo Bacellar Nunes Soares, gbnsoares@sga.pucminas.br**


---

Professores:

**Hugo Bastos de Paula**

**Hayala Nepomuceno Curto**

---

_Curso de Ciência de Dados, Unidade Praça da Liberdade_

_Instituto de Informática e Ciências Exatas – Pontifícia Universidade de Minas Gerais (PUC MINAS), Belo Horizonte – MG – Brasil_

---

**Resumo**. 

Este estudo investiga a disparidade de gênero no setor da tecnologia no Brasil, analisando os desafios enfrentados pelas mulheres. A pesquisa utiliza dados do State of Data Brazil 2023 para identificar diferenças na participação, salários e oportunidades de crescimento entre homens e mulheres no mercado de trabalho de dados. Um dos objetivos será  fornecer dados e insights que possam embasar políticas de inclusão, contribuindo para um mercado de trabalho mais diverso e inovador.

---


## Introdução

  É notório que o pensamento, tanto feminino quanto masculino, apresenta-se extremamente válido para o avanço tecnológico, inclusive no Setor da tecnologia no Brasil. Entretanto, tal realidade apresenta-se desvirtuada e validada por uma análise descritiva que pode ser realizada ao observar o banco de dados servindo como referência para esta pesquisa. Através de uma análise descritiva, esse estudo busca, primeiramente, validar tal infeliz realidade da disparidade (em todas as suas vertentes) de gênero no Setor da tecnologia no Brasil e então, propor alternativas válidas para a promoção da inclusão de gênero equalitária nesse nicho.  
  
  As causas que podem ser inferidas para esse desafio são várias e serão abordadas abaixo. Dentre elas, observa-se o imaginário social enraizado de que mulheres não são tão ábeis em tecnologia quanto os homens, além haver uma ausência de representatividade feminina nesse nicho, fora a dupla-jornada de trabalho que,normalmente, mulheres enfrentam, limitando ainda mais sua capacidade de cresimento, contribuição e evolução nesse ramo.  

  Essa pesquisa é importante uma vez que, com sua validação e correta execução, mais mulheres poderão ter lugar e espaço no Setor da tecnologia no Brasil. Com isso, além de fornecer mais rotatividade de empregos no mercado, mais vidas serão positivamente contribuídas pelo trabalho, com o incentivo, mesmo que sutil, a mais mulheres ingressando nesse ramo, sem haver disparidades, desigualdades ou destratamentos, haverão mais mentes pensantes dentro desse mercado, contribuindo para mais avanços científicos úteis para o mundo e o futuro, os quais podem estar sendo retardados pela presença de desvalorização da força feminina dentro desse mercado, tema pelo qual abordaremos com mais detalhes a seguir.

###    Contextualização

A área de ciência de dados cresce a passos largos, movimentando bilhões e influenciando decisões no mundo todo. Mas, quando olhamos para quem está por trás dessas análises e algoritmos, percebemos uma realidade preocupante: a disparidade de gênero ainda é grande. As mulheres continuam sub-representadas no setor, enfrentando barreiras que vão desde a entrada no mercado até a progressão na carreira.
Os números refletem essa realidade. Pesquisas mostram que a presença feminina na ciência de dados ainda é muito menor do que a masculina, e as chances de ocupar cargos de liderança são ainda mais reduzidas. Entender essa disparidade e buscar soluções para torná-la coisa do passado não é apenas uma questão de justiça – é também uma maneira de tornar o setor mais diverso, inovador e eficiente.

###    Problema

No Brasil, as mulheres que trabalham em setores da Tecnologia são prejudicadas por haver, intrinsicamente, uma disparidade de gênero em seu setor laboral. Tal problema ocorre por um viés social, por exemplo, por meio de esteriótipos sobre empregos ou, também, por um viés econômico, em que as mulheres perdem oportunidades de empregos ou de salários melhores para homens.
Dito isso, observa-se uma notória discrepância de gênero em um mercado de trabalho na área da computação.



###    Objetivo geral

 Desenvolver um sistema inteligente para classificar se a pessoa vai estar empregada ou desempregada conforme o gênero e a região onde ela mora.


####    Objetivos específicos

1- Analisar a distribuição de gênero entre os profissionais do setor de tecnologia

2-Comparar os salários médios entre homens e mulheres no setor de dados

3- Comparar as oportunidades de crescimento entre homens e mulheres no setor de dados

4- Identificar os principais desafios enfrentados por mulheres no setor de dados

5- Comparar a representatividade feminina em cargos de liderança no setor de dados

6- Examinar a relação entre nível de escolaridade e empregabilidade de mulheres no setor

7- Estudar a presença de viés de gênero nos processos seletivos do setor de tecnologia



###    Justificativas

A razão pela a escolha do tema Disparidade de gênero no setor de T.I vem da necessidade de apoiar a igualdade entre gêneros no mercado de dados, 
um lugar que ainda mostra diferenças grandes entre homens e mulheres. Ao olharmos para a diferença por gênero, 
tentamos achar as causas dessas desigualdades e dar números que podem ajudar políticas e ações de inclusão. 



##    Público alvo

O nosso público-alvo são gerentes de empresa que buscam uma menor disparidade de mulheres nos diversos setores da tecnologia, como gerentes de RH e chefes de setor de tecnologia.
Temos como público alvo diretores e coordenadores de instiruições de ensino da área, ja que podemos observar uma grande falta de mulheres nos cursos da área. Além de estudantes que buscam se graduar na área de tecnologia.

###  Personas

1️⃣ Persona: Desenvolvedora Plena em Tecnologia

- Nome: Carla Nunes

- Idade: 29 anos

- Objetivo: Entender se está sendo remunerada de forma justa em comparação aos colegas homens com funções similares.

- Desafios: Dificuldade em acessar dados transparentes e atualizados sobre salários com recorte de gênero.

2️⃣ Persona: Coordenadora de Diversidade e Inclusão

- Nome: Priscila Duarte

- Idade: 35 anos

- Objetivo: Desenvolver políticas internas que reduzam a desigualdade salarial de gênero.

- Desafios: Falta de indicadores específicos sobre mulheres em cargos técnicos e de liderança na empresa.

3️⃣ Persona: Engenheiro de Software Sênior

- Nome: Rafael Lima

- Idade: 41 anos

- Objetivo: Apoiar iniciativas de equidade de gênero no setor, incluindo revisão salarial.

- Desafios: Não tem acesso a comparativos salariais por gênero que possam embasar ações efetivas.

4️⃣ Persona: Consultora de Igualdade de Gênero em ONGs

- Nome: Sônia Ferreira

- Idade: 47 anos

- Objetivo: Promover ações públicas e privadas que eliminem a diferença salarial entre homens e mulheres na tecnologia.

- Desafios: Precisa de estudos aprofundados com dados desagregados por cargo, gênero, região e senioridade.


# Análise Exploratória - Disparidade de Gênero no Mercado de Trabalho

**Hipótese**: Investigar como a disparidade de gênero interfere na situação atual de trabalho conforme a região onde a pessoa mora.

---

###    Dicionário de dados

## Análise de Dados da Pesquisa State of Data BR 2023

## 1. Base de Dados Principal

* **Fonte:** Arquivo CSV 'State_of_data_BR_2023_Kaggle - df_survey_2023.csv' (processado no notebook).
* **Descrição:** Esta base de dados contém informações sobre profissionais e estudantes da área de dados no Brasil em 2023. Os dados foram processados para facilitar a análise, incluindo a seleção de colunas relevantes e a codificação de variáveis categóricas.

## 2. Dicionário de Dados da Base Principal

Dicionário de dados base principal
Claro. Peço desculpas pela resposta anterior que resumiu a saída.
Aqui está o dicionário de dados completo no formato Markdown para todas as 399 colunas da base de dados, conforme solicitado.
Markdown
| Atributo | Descrição | Tipo |
|---|---|---|
| P1_a_Idade | Idade do respondente | Inteiro |
| P1_b_Genero | Gênero do respondente | Textual |
| P1_c_Cor_raca | Cor ou raça autodeclarada pelo respondente | Textual |
| P1_d_PCD | Indica se o respondente é uma pessoa com deficiência | Textual |
| P1_e_experiencia_profissional | Tempo de experiência profissional na área de dados | Textual |
| P1_f_estado_onde_nasceu | Estado de nascimento do respondente | Textual |
| P1_g_estado_onde_mora | Estado de residência atual do respondente | Textual |
| P1_h_possui_graduacao | Indica se o respondente possui diploma de graduação | Textual |
| P2_a_formacao_academica | Nível mais alto de formação acadêmica | Textual |
| P2_b_area_formacao | Área de formação principal do respondente | Textual |
| P2_c_foi_influenciado_a_entrar_na_area_de_dados | Nota de influência para entrar na área de dados | Inteiro |
| P2_e_se_considera_data_literate | Nota de autoavaliação de alfabetização em dados | Inteiro |
| P2_f_nivel_ingles | Nível de proficiência em inglês | Textual |
| P3_a_situacao_trabalho_atual | Situação de trabalho atual na área de dados | Textual |
| P4_a_cargo_atual | Cargo atual ou mais recente do respondente | Textual |
| P4_b_escolaridade_recomendada_para_cargo | Escolaridade recomendada para o cargo atual | Textual |
| P4_c_faixa_salarial | Faixa salarial mensal em Reais (R$) | Textual |
| P4_d_media_salario_area | Percepção do salário em relação à média da área | Inteiro |
| P4_e_pretensao_salarial_proximos_2_anos | Pretensão salarial para os próximos 2 anos | Textual |
| P4_f_setor_empresa | Setor de atuação da empresa | Textual |
| P4_g_tamanho_empresa | Porte da empresa onde trabalha | Textual |
| P4_h_regiao_empresa | Região da empresa | Textual |
| P4_i_modelo_trabalho | Modelo de trabalho (Presencial, Híbrido, Remoto) | Textual |
| P4_j_ambiente_trabalho_preferido | Preferência de ambiente de trabalho | Textual |
| P4_l_tipo_contrato_trabalho | Tipo de contrato de trabalho (CLT, PJ, etc.) | Textual |
| P4_m_nivel_satisfacao_trabalho | Nível de satisfação com o trabalho atual | Inteiro |
| P5_b_investe_em_educacao_continuada | Resposta sobre o investimento em educação continuada | Textual |
| P5_c_horas_estudo_semanais | Horas de estudo dedicadas à área de dados por semana | Inteiro |
| P6_a_preocupacao_ia_substituir_trabalho | Nível de preocupação sobre IA substituir seu trabalho | Inteiro |
| P6_b_entendimento_ia_generativa | Nível de entendimento sobre IA Generativa | Inteiro |
| P6_c_uso_ia_generativa_trabalho | Indica se utiliza IA Generativa no trabalho | Textual |
| P6_e_opiniao_regulamentacao_ia | Opinião sobre a regulamentação do uso de IA | Textual |
| P1_i_tipo_graduacao_Bacharelado | Resposta binária (0/1) para a opção 'Bacharelado' na pergunta 'Tipo de Graduação' | Inteiro |
| P1_i_tipo_graduacao_Licenciatura | Resposta binária (0/1) para a opção 'Licenciatura' na pergunta 'Tipo de Graduação' | Inteiro |
| P1_i_tipo_graduacao_Tecnólogo | Resposta binária (0/1) para a opção 'Tecnólogo' na pergunta 'Tipo de Graduação' | Inteiro |
| P1_i_tipo_graduacao_Pós-graduação | Resposta binária (0/1) para a opção 'Pós-graduação' na pergunta 'Tipo de Graduação' | Inteiro |
| P1_i_tipo_graduacao_Mestrado | Resposta binária (0/1) para a opção 'Mestrado' na pergunta 'Tipo de Graduação' | Inteiro |
| P1_i_tipo_graduacao_Doutorado | Resposta binária (0/1) para a opção 'Doutorado' na pergunta 'Tipo de Graduação' | Inteiro |
| P1_i_tipo_graduacao_Não conclui a graduação | Resposta binária (0/1) para a opção 'Não concluí a graduação' na pergunta 'Tipo de Graduação' | Inteiro |
| P1_i_tipo_graduacao_Outro | Resposta binária (0/1) para a opção 'Outro' na pergunta 'Tipo de Graduação' | Inteiro |
| P2_d_motivacao_area_dados_Gosto de programação | Resposta binária (0/1) para a opção 'Gosto de programação' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Gosto de matemática e estatística | Resposta binária (0/1) para a opção 'Gosto de matemática e estatística' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Estou fazendo uma transição de carreira | Resposta binária (0/1) para a opção 'Estou fazendo uma transição de carreira' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Oportunidade de trabalhar remotamente | Resposta binária (0/1) para a opção 'Oportunidade de trabalhar remotamente' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Área com boas oportunidades de crescimento | Resposta binária (0/1) para a opção 'Área com boas oportunidades de crescimento' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Bons salários | Resposta binária (0/1) para a opção 'Bons salários' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Sou novo no mercado de trabalho | Resposta binária (0/1) para a opção 'Sou novo no mercado de trabalho' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Já trabalhava com dados | Resposta binária (0/1) para a opção 'Já trabalhava com dados' na pergunta 'Motivação para entrar na área' | Inteiro |
| P2_d_motivacao_area_dados_Outra motivação | Resposta binária (0/1) para a opção 'Outra motivação' na pergunta 'Motivação para entrar na área' | Inteiro |
| P3_b_principal_linguagem_programacao_Python | Resposta binária (0/1) para a opção 'Python' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_R | Resposta binária (0/1) para a opção 'R' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_SQL | Resposta binária (0/1) para a opção 'SQL' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_VBA | Resposta binária (0/1) para a opção 'VBA' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_SAS/Stata | Resposta binária (0/1) para a opção 'SAS/Stata' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_Java | Resposta binária (0/1) para a opção 'Java' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_C/C++/C# | Resposta binária (0/1) para a opção 'C/C++/C#' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_Javascript/Typescript | Resposta binária (0/1) para a opção 'Javascript/Typescript' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_PHP | Resposta binária (0/1) para a opção 'PHP' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_Não utilizo nenhuma linguagem | Resposta binária (0/1) para a opção 'Não utilizo nenhuma linguagem' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_b_principal_linguagem_programacao_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Principal linguagem de programação' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_Python | Resposta binária (0/1) para a opção 'Python' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_R | Resposta binária (0/1) para a opção 'R' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_SQL | Resposta binária (0/1) para a opção 'SQL' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_VBA | Resposta binária (0/1) para a opção 'VBA' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_SAS/Stata | Resposta binária (0/1) para a opção 'SAS/Stata' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_Java | Resposta binária (0/1) para a opção 'Java' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_C/C++/C# | Resposta binária (0/1) para a opção 'C/C++/C#' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_Javascript/Typescript | Resposta binária (0/1) para a opção 'Javascript/Typescript' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_PHP | Resposta binária (0/1) para a opção 'PHP' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_Não utilizo nenhuma linguagem | Resposta binária (0/1) para a opção 'Não utilizo nenhuma linguagem' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Linguagens mais usadas' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Power BI | Resposta binária (0/1) para a opção 'Power BI' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Tableau | Resposta binária (0/1) para a opção 'Tableau' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Qlik Sense/Qlik View | Resposta binária (0/1) para a opção 'Qlik' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Looker | Resposta binária (0/1) para a opção 'Looker' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Microstrategy | Resposta binária (0/1) para a opção 'Microstrategy' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Metabase | Resposta binária (0/1) para a opção 'Metabase' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Superset | Resposta binária (0/1) para a opção 'Superset' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Redash | Resposta binária (0/1) para a opção 'Redash' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_SAS Visual Analytics | Resposta binária (0/1) para a opção 'SAS VA' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Pentaho | Resposta binária (0/1) para a opção 'Pentaho' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Excel | Resposta binária (0/1) para a opção 'Excel' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Não utilizo ferramentas de BI | Resposta binária (0/1) para a opção 'Não utilizo' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Ferramentas de BI' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Amazon Web Services (AWS) | Resposta binária (0/1) para a opção 'AWS' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Google Cloud (GCP) | Resposta binária (0/1) para a opção 'GCP' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Microsoft Azure | Resposta binária (0/1) para a opção 'Azure' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Oracle | Resposta binária (0/1) para a opção 'Oracle' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_IBM | Resposta binária (0/1) para a opção 'IBM' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Hadoop | Resposta binária (0/1) para a opção 'Hadoop' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Cloudera | Resposta binária (0/1) para a opção 'Cloudera' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Databricks | Resposta binária (0/1) para a opção 'Databricks' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Snowflake | Resposta binária (0/1) para a opção 'Snowflake' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Não utilizo nenhuma | Resposta binária (0/1) para a opção 'Não utilizo' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Plataformas de Nuvem' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Apache Airflow | Resposta binária (0/1) para a opção 'Apache Airflow' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_AWS Glue | Resposta binária (0/1) para a opção 'AWS Glue' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Google Dataflow | Resposta binária (0/1) para a opção 'Google Dataflow' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Azure Data Factory | Resposta binária (0/1) para a opção 'Azure Data Factory' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_IBM DataStage | Resposta binária (0/1) para a opção 'IBM DataStage' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Oracle Data Integrator | Resposta binária (0/1) para a opção 'Oracle Data Integrator' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Talend | Resposta binária (0/1) para a opção 'Talend' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_SAP | Resposta binária (0/1) para a opção 'SAP' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Pentaho | Resposta binária (0/1) para a opção 'Pentaho' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Alteryx | Resposta binária (0/1) para a opção 'Alteryx' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_dbt | Resposta binária (0/1) para a opção 'dbt' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Não utilizo nenhuma | Resposta binária (0/1) para a opção 'Não utilizo' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Ferramentas de ETL' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_SQL | Resposta binária (0/1) para a opção 'SQL' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_Python | Resposta binária (0/1) para a opção 'Python' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_R | Resposta binária (0/1) para a opção 'R' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_SAS/Stata | Resposta binária (0/1) para a opção 'SAS/Stata' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_Excel/Google Sheets | Resposta binária (0/1) para a opção 'Excel/Sheets' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_MATLAB | Resposta binária (0/1) para a opção 'MATLAB' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_SPSS | Resposta binária (0/1) para a opção 'SPSS' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_Knime | Resposta binária (0/1) para a opção 'Knime' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_Alteryx | Resposta binária (0/1) para a opção 'Alteryx' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_Não utilizo nenhuma | Resposta binária (0/1) para a opção 'Não utilizo' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Ferramentas de Modelagem' | Inteiro |
| P3_h_banco_de_dados_mais_usados_MySQL | Resposta binária (0/1) para a opção 'MySQL' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_PostgreSQL | Resposta binária (0/1) para a opção 'PostgreSQL' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Microsoft SQL Server | Resposta binária (0/1) para a opção 'SQL Server' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Oracle Database | Resposta binária (0/1) para a opção 'Oracle' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_IBM DB2 | Resposta binária (0/1) para a opção 'DB2' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_SAP HANA | Resposta binária (0/1) para a opção 'SAP HANA' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Amazon Redshift | Resposta binária (0/1) para a opção 'Redshift' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Google BigQuery | Resposta binária (0/1) para a opção 'BigQuery' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Apache Hive | Resposta binária (0/1) para a opção 'Hive' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_MongoDB | Resposta binária (0/1) para a opção 'MongoDB' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Cassandra | Resposta binária (0/1) para a opção 'Cassandra' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Elasticsearch | Resposta binária (0/1) para a opção 'Elasticsearch' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Databricks/Delta Lake | Resposta binária (0/1) para a opção 'Databricks' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Snowflake | Resposta binária (0/1) para a opção 'Snowflake' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Não utilizo nenhum | Resposta binária (0/1) para a opção 'Não utilizo' na pergunta 'Bancos de Dados' | Inteiro |
| P3_h_banco_de_dados_mais_usados_Outro | Resposta binária (0/1) para a opção 'Outro' na pergunta 'Bancos de Dados' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Hadoop | Resposta binária (0/1) para a opção 'Hadoop' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Cloudera | Resposta binária (0/1) para a opção 'Cloudera' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Databricks | Resposta binária (0/1) para a opção 'Databricks' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Amazon EMR | Resposta binária (0/1) para a opção 'Amazon EMR' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Google Dataproc | Resposta binária (0/1) para a opção 'Google Dataproc' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Azure HDInsight | Resposta binária (0/1) para a opção 'Azure HDInsight' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Apache Spark | Resposta binária (0/1) para a opção 'Apache Spark' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Apache Flink | Resposta binária (0/1) para a opção 'Apache Flink' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Apache Kafka | Resposta binária (0/1) para a opção 'Apache Kafka' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_MongoDB | Resposta binária (0/1) para a opção 'MongoDB' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Cassandra | Resposta binária (0/1) para a opção 'Cassandra' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Elasticsearch | Resposta binária (0/1) para a opção 'Elasticsearch' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Não utilizo nenhuma | Resposta binária (0/1) para a opção 'Não utilizo' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Plataformas de Big Data' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_Scikit-learn | Resposta binária (0/1) para a opção 'Scikit-learn' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_TensorFlow | Resposta binária (0/1) para a opção 'TensorFlow' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_PyTorch | Resposta binária (0/1) para a opção 'PyTorch' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_Keras | Resposta binária (0/1) para a opção 'Keras' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_XGBoost | Resposta binária (0/1) para a opção 'XGBoost' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_LightGBM | Resposta binária (0/1) para a opção 'LightGBM' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_FastAI | Resposta binária (0/1) para a opção 'FastAI' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_Spacy | Resposta binária (0/1) para a opção 'Spacy' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_NLTK | Resposta binária (0/1) para a opção 'NLTK' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_HuggingFace | Resposta binária (0/1) para a opção 'HuggingFace' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_MLflow | Resposta binária (0/1) para a opção 'MLflow' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_Não utilizo nenhuma | Resposta binária (0/1) para a opção 'Não utilizo' na pergunta 'Bibliotecas de IA' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Bibliotecas de IA' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Aprender novas ferramentas e tecnologias | Resposta binária (0/1) para a opção 'Aprender novas ferramentas' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Mais desafios e responsabilidades | Resposta binária (0/1) para a opção 'Mais desafios' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Melhor equilíbrio entre vida pessoal e profissional | Resposta binária (0/1) para a opção 'Melhor equilíbrio' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Mudar de área de atuação | Resposta binária (0/1) para a opção 'Mudar de área' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Oportunidade de liderar pessoas | Resposta binária (0/1) para a opção 'Oportunidade de liderar' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Oportunidade de trabalhar em outra empresa | Resposta binária (0/1) para a opção 'Trabalhar em outra empresa' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Salário mais alto | Resposta binária (0/1) para a opção 'Salário mais alto' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Trabalhar remotamente | Resposta binária (0/1) para a opção 'Trabalhar remotamente' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Prioridade próxima oportunidade' | Inteiro |
| P4_n_recebe_beneficios_Vale-alimentação | Resposta binária (0/1) para a opção 'Vale-alimentação' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Vale-refeição | Resposta binária (0/1) para a opção 'Vale-refeição' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Plano de saúde | Resposta binária (0/1) para a opção 'Plano de saúde' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Plano odontológico | Resposta binária (0/1) para a opção 'Plano odontológico' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Auxílio-creche | Resposta binária (0/1) para a opção 'Auxílio-creche' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Seguro de vida | Resposta binária (0/1) para a opção 'Seguro de vida' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Previdência privada | Resposta binária (0/1) para a opção 'Previdência privada' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_PLR | Resposta binária (0/1) para a opção 'PLR' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Horário flexível | Resposta binária (0/1) para a opção 'Horário flexível' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Auxílio home-office | Resposta binária (0/1) para a opção 'Auxílio home-office' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Auxílio educação/estudo | Resposta binária (0/1) para a opção 'Auxílio educação/estudo' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Ações da empresa (Stock Options) | Resposta binária (0/1) para a opção 'Ações da empresa' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Não recebo nenhum benefício | Resposta binária (0/1) para a opção 'Não recebo nenhum' na pergunta 'Benefícios recebidos' | Inteiro |
| P4_n_recebe_beneficios_Outro | Resposta binária (0/1) para a opção 'Outro' na pergunta 'Benefícios recebidos' | Inteiro |
| P5_a_plataformas_conteudo_dados_Blogs/Artigos (Medium, Towards Data Science, etc) | Resposta binária (0/1) para a opção 'Blogs/Artigos' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Cursos online (Udemy, Coursera, etc) | Resposta binária (0/1) para a opção 'Cursos online' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Eventos/meetups/conferências | Resposta binária (0/1) para a opção 'Eventos/meetups' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Fóruns (Stack Overflow, Reddit, etc) | Resposta binária (0/1) para a opção 'Fóruns' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_LinkedIn | Resposta binária (0/1) para a opção 'LinkedIn' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Livros | Resposta binária (0/1) para a opção 'Livros' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Newsletters | Resposta binária (0/1) para a opção 'Newsletters' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Podcasts | Resposta binária (0/1) para a opção 'Podcasts' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Twitter | Resposta binária (0/1) para a opção 'Twitter' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Vídeos no YouTube | Resposta binária (0/1) para a opção 'Vídeos no YouTube' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Comunidades do WhatsApp/Telegram/Discord | Resposta binária (0/1) para a opção 'Comunidades' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_a_plataformas_conteudo_dados_Outro | Resposta binária (0/1) para a opção 'Outro' na pergunta 'Plataformas de conteúdo' | Inteiro |
| P5_d_plataformas_estudo_dados_Udemy | Resposta binária (0/1) para a opção 'Udemy' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Coursera | Resposta binária (0/1) para a opção 'Coursera' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_edX | Resposta binária (0/1) para a opção 'edX' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_DataCamp | Resposta binária (0/1) para a opção 'DataCamp' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Alura | Resposta binária (0/1) para a opção 'Alura' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Udacity | Resposta binária (0/1) para a opção 'Udacity' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_LinkedIn Learning | Resposta binária (0/1) para a opção 'LinkedIn Learning' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_YouTube | Resposta binária (0/1) para a opção 'YouTube' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Kaggle Learn | Resposta binária (0/1) para a opção 'Kaggle Learn' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Cursos de empresas de tecnologia (AWS, Google, Microsoft, etc) | Resposta binária (0/1) para a opção 'Cursos de empresas' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Cursos de escolas de dados (Data Science Academy, etc) | Resposta binária (0/1) para a opção 'Cursos de escolas de dados' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Não estudo por nenhuma plataforma | Resposta binária (0/1) para a opção 'Não estudo' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_d_plataformas_estudo_dados_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Plataformas de estudo' | Inteiro |
| P5_e_desafios_carreira_dados_Falta de oportunidades de crescimento na minha empresa | Resposta binária (0/1) para a opção 'Falta de oportunidades' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Falta de maturidade da empresa em relação à cultura de dados | Resposta binária (0/1) para a opção 'Falta de maturidade da empresa' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Infraestrutura de dados inadequada | Resposta binária (0/1) para a opção 'Infraestrutura inadequada' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Qualidade dos dados ruins | Resposta binária (0/1) para a opção 'Qualidade dos dados ruins' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Comunicação com outras áreas da empresa | Resposta binária (0/1) para a opção 'Comunicação com outras áreas' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Burocracia para colocar projetos em produção | Resposta binária (0/1) para a opção 'Burocracia' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Falta de clareza ou definição de um plano de carreira | Resposta binária (0/1) para a opção 'Falta de clareza no plano de carreira' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Dificuldade em me manter atualizado | Resposta binária (0/1) para a opção 'Dificuldade em me manter atualizado' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Síndrome do Impostor | Resposta binária (0/1) para a opção 'Síndrome do Impostor' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Excesso de reuniões | Resposta binária (0/1) para a opção 'Excesso de reuniões' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Salário abaixo da média do mercado | Resposta binária (0/1) para a opção 'Salário abaixo da média' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Nenhum desafio | Resposta binária (0/1) para a opção 'Nenhum desafio' na pergunta 'Desafios na carreira' | Inteiro |
| P5_e_desafios_carreira_dados_Outro | Resposta binária (0/1) para a opção 'Outro' na pergunta 'Desafios na carreira' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_ChatGPT | Resposta binária (0/1) para a opção 'ChatGPT' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Google Bard/Gemini | Resposta binária (0/1) para a opção 'Google Bard/Gemini' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Microsoft Copilot | Resposta binária (0/1) para a opção 'Microsoft Copilot' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Github Copilot | Resposta binária (0/1) para a opção 'Github Copilot' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Claude | Resposta binária (0/1) para a opção 'Claude' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Midjourney | Resposta binária (0/1) para a opção 'Midjourney' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_DALL-E | Resposta binária (0/1) para a opção 'DALL-E' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Notion AI | Resposta binária (0/1) para a opção 'Notion AI' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Nenhuma | Resposta binária (0/1) para a opção 'Nenhuma' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_Outra | Resposta binária (0/1) para a opção 'Outra' na pergunta 'Ferramentas de IA Generativa' | Inteiro |
| P1_i_tipo_graduacao_nan | Resposta binária (0/1) indicando ausência de resposta para 'Tipo de Graduação' | Inteiro |
| P2_d_motivacao_area_dados_nan | Resposta binária (0/1) indicando ausência de resposta para 'Motivação para entrar na área' | Inteiro |
| P3_b_principal_linguagem_programacao_nan | Resposta binária (0/1) indicando ausência de resposta para 'Principal linguagem de programação' | Inteiro |
| P3_c_linguagens_de_programacao_mais_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Linguagens mais usadas' | Inteiro |
| P3_d_ferramentas_bi_mais_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Ferramentas de BI' | Inteiro |
| P3_e_plataformas_nuvem_mais_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Plataformas de Nuvem' | Inteiro |
| P3_f_ferramentas_etl_mais_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Ferramentas de ETL' | Inteiro |
| P3_g_ferramentas_de_modelagem_de_dados_mais_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Ferramentas de Modelagem' | Inteiro |
| P3_h_banco_de_dados_mais_usados_nan | Resposta binária (0/1) indicando ausência de resposta para 'Bancos de Dados' | Inteiro |
| P3_i_plataformas_de_big_data_mais_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Plataformas de Big Data' | Inteiro |
| P3_j_bibliotecas_de_ia_mais_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Bibliotecas de IA' | Inteiro |
| P4_k_prioridade_proxima_oportunidade_nan | Resposta binária (0/1) indicando ausência de resposta para 'Prioridade próxima oportunidade' | Inteiro |
| P4_n_recebe_beneficios_nan | Resposta binária (0/1) indicando ausência de resposta para 'Benefícios recebidos' | Inteiro |
| P5_a_plataformas_conteudo_dados_nan | Resposta binária (0/1) indicando ausência de resposta para 'Plataformas de conteúdo' | Inteiro |
| P5_d_plataformas_estudo_dados_nan | Resposta binária (0/1) indicando ausência de resposta para 'Plataformas de estudo' | Inteiro |
| P5_e_desafios_carreira_dados_nan | Resposta binária (0/1) indicando ausência de resposta para 'Desafios na carreira' | Inteiro |
| P6_d_ferramentas_ia_generativa_usadas_nan | Resposta binária (0/1) indicando ausência de resposta para 'Ferramentas de IA Generativa' | Inteiro |
| cargo_atual_Analista de BI/BI Analyst | Resposta binária (0/1) para o cargo 'Analista de BI' | Inteiro |
| cargo_atual_Analista de Dados/Data Analyst | Resposta binária (0/1) para o cargo 'Analista de Dados' | Inteiro |
| cargo_atual_Cientista de Dados/Data Scientist | Resposta binária (0/1) para o cargo 'Cientista de Dados' | Inteiro |
| cargo_atual_Engenheiro de Dados/Data Engineer | Resposta binária (0/1) para o cargo 'Engenheiro de Dados' | Inteiro |
| cargo_atual_Engenheiro de Machine Learning/Machine Learning Engineer | Resposta binária (0/1) para o cargo 'Engenheiro de Machine Learning' | Inteiro |
| cargo_atual_Engenheiro de Analytics/Analytics Engineer | Resposta binária (0/1) para o cargo 'Engenheiro de Analytics' | Inteiro |
| cargo_atual_Especialista/Arquiteto(a) de Dados | Resposta binária (0/1) para o cargo 'Especialista/Arquiteto de Dados' | Inteiro |
| cargo_atual_Líder Técnico/Tech Lead | Resposta binária (0/1) para o cargo 'Líder Técnico' | Inteiro |
| cargo_atual_Coordenador/Manager | Resposta binária (0/1) para o cargo 'Coordenador/Manager' | Inteiro |
| cargo_atual_Outro | Resposta binária (0/1) para o cargo 'Outro' | Inteiro |
| cargo_atual_nan | Resposta binária (0/1) indicando ausência de resposta para 'Cargo Atual' | Inteiro |
| area_formacao_Ciências da Computação, Engenharia de Software, Sistemas de Informação, etc. | Resposta binária (0/1) para a área de formação 'Computação' | Inteiro |
| area_formacao_Engenharias (outras) | Resposta binária (0/1) para a área de formação 'Outras Engenharias' | Inteiro |
| area_formacao_Estatística | Resposta binária (0/1) para a área de formação 'Estatística' | Inteiro |
| area_formacao_Economia, Administração, Contabilidade, etc. | Resposta binária (0/1) para a área de formação 'Negócios' | Inteiro |
| area_formacao_Ciências Sociais, Marketing, etc. | Resposta binária (0/1) para a área de formação 'Ciências Sociais/Marketing' | Inteiro |
| area_formacao_Ciências Exatas (Matemática, Física, etc.) | Resposta binária (0/1) para a área de formação 'Ciências Exatas' | Inteiro |
| area_formacao_Outra | Resposta binária (0/1) para a área de formação 'Outra' | Inteiro |
| area_formacao_nan | Resposta binária (0/1) indicando ausência de resposta para 'Área de Formação' | Inteiro |
| situacao_trabalho_atual_Empregado (CLT) | Resposta binária (0/1) para a situação 'Empregado (CLT)' | Inteiro |
| situacao_trabalho_atual_Empregado (Servidor Público) | Resposta binária (0/1) para a situação 'Empregado (Servidor Público)' | Inteiro |
| situacao_trabalho_atual_Contrato (PJ) | Resposta binária (0/1) para a situação 'Contrato (PJ)' | Inteiro |
| situacao_trabalho_atual_Freelancer | Resposta binária (0/1) para a situação 'Freelancer' | Inteiro |
| situacao_trabalho_atual_Estagiário | Resposta binária (0/1) para a situação 'Estagiário' | Inteiro |
| situacao_trabalho_atual_Desempregado, buscando recolocação | Resposta binária (0/1) para a situação 'Desempregado' | Inteiro |
| situacao_trabalho_atual_Apenas estudando | Resposta binária (0/1) para a situação 'Apenas estudando' | Inteiro |
| situacao_trabalho_atual_Outra | Resposta binária (0/1) para a situação 'Outra' | Inteiro |
| situacao_trabalho_atual_nan | Resposta binária (0/1) indicando ausência de resposta para 'Situação de Trabalho' | Inteiro |
| faixa_salarial_Menos de R$ 1.000/mês | Resposta binária (0/1) para a faixa salarial 'Menos de R$ 1.000' | Inteiro |
| faixa_salarial_de R$ 1.001/mês a R$ 2.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 1.001 a R$ 2.000' | Inteiro |
| faixa_salarial_de R$ 2.001/mês a R$ 3.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 2.001 a R$ 3.000' | Inteiro |
| faixa_salarial_de R$ 3.001/mês a R$ 4.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 3.001 a R$ 4.000' | Inteiro |
| faixa_salarial_de R$ 4.001/mês a R$ 6.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 4.001 a R$ 6.000' | Inteiro |
| faixa_salarial_de R$ 6.001/mês a R$ 8.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 6.001 a R$ 8.000' | Inteiro |
| faixa_salarial_de R$ 8.001/mês a R$ 12.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 8.001 a R$ 12.000' | Inteiro |
| faixa_salarial_de R$ 12.001/mês a R$ 16.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 12.001 a R$ 16.000' | Inteiro |
| faixa_salarial_de R$ 16.001/mês a R$ 20.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 16.001 a R$ 20.000' | Inteiro |
| faixa_salarial_de R$ 20.001/mês a R$ 25.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 20.001 a R$ 25.000' | Inteiro |
| faixa_salarial_de R$ 25.001/mês a R$ 30.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 25.001 a R$ 30.000' | Inteiro |
| faixa_salarial_de R$ 30.001/mês a R$ 40.000/mês | Resposta binária (0/1) para a faixa salarial 'R$ 30.001 a R$ 40.000' | Inteiro |
| faixa_salarial_Mais de R$ 40.000/mês | Resposta binária (0/1) para a faixa salarial 'Mais de R$ 40.000' | Inteiro |
| faixa_salarial_nan | Resposta binária (0/1) indicando ausência de resposta para 'Faixa Salarial' | Inteiro |
| nivel_ingles_Nenhum | Resposta binária (0/1) para o nível de inglês 'Nenhum' | Inteiro |
| nivel_ingles_Básico | Resposta binária (0/1) para o nível de inglês 'Básico' | Inteiro |
| nivel_ingles_Intermediário | Resposta binária (0/1) para o nível de inglês 'Intermediário' | Inteiro |
| nivel_ingles_Avançado | Resposta binária (0/1) para o nível de inglês 'Avançado' | Inteiro |
| nivel_ingles_Fluente | Resposta binária (0/1) para o nível de inglês 'Fluente' | Inteiro |
| nivel_ingles_nan | Resposta binária (0/1) indicando ausência de resposta para 'Nível de Inglês' | Inteiro |
| experiencia_profissional_Sem experiência | Resposta binária (0/1) para a experiência 'Sem experiência' | Inteiro |
| experiencia_profissional_Menos de 1 ano | Resposta binária (0/1) para a experiência 'Menos de 1 ano' | Inteiro |
| experiencia_profissional_de 1 a 2 anos | Resposta binária (0/1) para a experiência 'de 1 a 2 anos' | Inteiro |
| experiencia_profissional_de 2 a 3 anos | Resposta binária (0/1) para a experiência 'de 2 a 3 anos' | Inteiro |
| experiencia_profissional_de 4 a 5 anos | Resposta binária (0/1) para a experiência 'de 4 a 5 anos' | Inteiro |
| experiencia_profissional_de 6 a 10 anos | Resposta binária (0/1) para a experiência 'de 6 a 10 anos' | Inteiro |
| experiencia_profissional_Mais de 10 anos | Resposta binária (0/1) para a experiência 'Mais de 10 anos' | Inteiro |
| experiencia_profissional_nan | Resposta binária (0/1) indicando ausência de resposta para 'Experiência Profissional' | Inteiro |



## Base auxiliar

# Dicionário de Dados - RELAÇÃO ANUAL DE INFORMAÇÕES SOCIAIS – RAIS

| Atributo | Descrição | Tipo |
| :--- | :--- | :--- |
| **Município** | Código do município (segundo o IBGE) onde o vínculo de trabalho está localizado. | Categórico |
| **CNAE 2.0 Classe** | Código da atividade econômica principal do estabelecimento, com base na Classificação Nacional de Atividades Econômicas (CNAE 2.0). | Categórico |
| **CBO Ocupação 2002** | Código da ocupação do trabalhador, com base na Classificação Brasileira de Ocupações (CBO), versão 2002. | Categórico |
| **Faixa Etária** | Intervalo de idade em que o trabalhador se encontra. | Categórico |
| **Escolaridade após 2005**| Nível de instrução formal do trabalhador. | Categórico |
| **Raça Cor** | Raça ou cor autodeclarada pelo trabalhador, seguindo as categorias do IBGE. | Categórico |
| **Sexo Trabalhador** | Sexo do trabalhador. | Categórico |
| **Vl Remun Média (SM)** | Valor da remuneração média mensal do trabalhador, expressa em quantidade de salários mínimos (SM). | Real |
| **Ind Trab Intermitente** | Indicador que aponta se o contrato de trabalho é do tipo intermitente (1 para Sim, 0 para Não). | Categórico |
| **Ind Trab Parcial** | Indicador que aponta se o contrato de trabalho é em regime de tempo parcial (1 para Sim, 0 para Não). | Categórico |
| **Tipo Vínculo** | Natureza do vínculo empregatício (ex: CLT, Estatutário). | Categórico |
| **Qtd Vínculos** | Número total de vínculos de trabalho existentes para o agrupamento de características da respectiva linha. | Inteiro |

### Observação: Agregamos à base principal usando o atributo Região onde mora, como atributo chave. 


## Preparação dos Dados

A fase de preparação dos dados é crucial para garantir a qualidade e adequação do dataset para a análise. Neste projeto, a preparação dos dados consistiu nos seguintes passos:

### Seleção dos Atributos

Com base no objetivo da análise e na hipótese a ser investigada, foi realizada a seleção manual dos atributos relevantes do dataset original. Os atributos selecionados para compor a base de dados principal foram:

* Idade
* Genero
* Cor/raca/etnia
* PCD (Pessoa com Deficiência)
* Regiao onde mora
* Nível de Ensino
* Área de formação em dados
* Situação de trabalho
* Estoque de Emprego Região (base auxiliar)

Estes atributos foram considerados essenciais para explorar as relações entre gênero, situação de trabalho e localização geográfica, além de fornecerem contexto demográfico e educacional dos respondentes.

### Tratamento dos Valores Faltantes ou Omissos

A presença de valores faltantes ou omissos nos dados pode impactar a análise. No processo de preparação, identificamos e tratamos esses valores:

* A categoria "Outras Engenharias" foi removida, pois não há dados nessa classe; 'nan' - nulos.
* "Outra opção" recebeu o mesmo valor que "Computação / Engenharia / Sistemas de Informação / TI" (0), pois a moda da àrea de fomação era a classe '0', então atribui 'Outra opção' a essa classe.
* Linhas com valores NaN nesta coluna foram removidas durante o processamento.
* *Linhas com valor “Prefiro não informar” em PCD foram removidas do DataFrame.*
* *Linhas com valor “Outro” em gênero foram removidas do DataFrame.*

### Tratamento dos Valores Inconsistentes

Valores inconsistentes podem distorcer os resultados da análise. Foram realizados tratamentos específicos para lidar com inconsistências identificadas:

* **Tratamento na Coluna 'Genero':** As categorias 'Outro' e 'Prefiro não informar' na coluna 'Genero' foram identificadas como inconsistentes para a análise de disparidade de gênero binária. Essas linhas foram removidas do dataset.
* **Tratamento na Coluna 'PCD':** Similarmente, as linhas onde a coluna 'PCD' apresentava o valor 'Prefiro não informar' foram removidas, pois não era possível inferir a informação de deficiência a partir desse valor.
* **Tratamento na Coluna 'Área de formação':** Foram identificados valores nulos (NaN) na coluna 'Área de formação' após o mapeamento, o que indicava a falta de informação para algumas entradas. As linhas com valores nulos nesta coluna também foram removidas.
* **Agrupamento na Coluna 'Situação de trabalho':** As diversas categorias de situação de trabalho foram agrupadas em duas categorias principais: 'Empregado(a)' e 'Desempregado(a)'. Este agrupamento simplifica a análise e foca na dicotomia emprego/desemprego. (É importante verificar e corrigir quaisquer erros de digitação durante este agrupamento).
* **Tratamento de Mapeamentos Duplicados/Inconsistentes:** Durante a codificação de variáveis categóricas, foi observado que a categoria 'Outras Engenharias' na coluna 'Área de formação' foi mapeada para dois valores diferentes (2 e 8), e 'Outra opção' foi mapeada para o mesmo valor que 'Computação / Engenharia...' (0). Embora o código original mostre esses mapeamentos, para uma análise precisa, estes devem ser revisados e corrigidos para garantir a unicidade dos códigos para cada categoria.


##  Conversão de Dados em `base_princ`

Esta seção detalha as transformações aplicadas às colunas da base de dados `base_princ` para converter todas as variáveis em categóricas
-

### **1. Discretização (*Binning*)**

Esta transformação foi aplicada para converter a variável numérica contínua `Idade` em uma variável categórica ordinal.

| Coluna Alvo | Transformação | Lógica | Novas Categorias (Rótulos) | Resultado |
| :--- | :--- | :--- | :--- | :--- |
| `Idade` | Agrupamento por Quartis (`pd.cut`) | A coluna foi dividida em 4 grupos de tamanho aproximadamente igual. | `Faixa_1_Idade`, `Faixa_2_Idade`, `Faixa_3_Idade`, `Faixa_4_Idade` | Criação da coluna `Faixa Etária` e remoção da coluna `Idade` original. |

---

### **2. Codificação por Rótulo (*Label Encoding*)**

Aplicada para converter variáveis categóricas binárias ou ordinais em valores numéricos.

| Coluna Alvo | Valor Original (Categoria) | Valor Novo (Numérico) |
| :--- | :--- | :--- |
| **Nível de Ensino** | `Não tenho graduação formal` | `0` |
| | `Estudante de Graduação` | `1` |
| | `Graduação/Bacharelado` | `2` |
| | `Pós-graduação` | `3` |
| | `Mestrado` | `4` |
| | `Doutorado ou Phd` | `5` |
| **Área de formação em tecnologia** | `Não` | `0` |
| | `Sim` | `1` |
| **Genero** | `Masculino` | `0` |
| | `Feminino` | `1` |
| **Situação de trabalho** | `Empregado(a)` | `0` |
| | `Desempregado(a)` | `1` |
| **PCD** | `Não` | `0` |
| | `Sim` | `1` |

**Observação:** Para as colunas `Genero`, `Situação de trabalho` e `PCD`, as linhas que não puderam ser mapeadas (por conterem valores nulos ou diferentes dos especificados) foram removidas da base (`dropna()`).

---

### **3. Codificação Fictícia (*One-Hot Encoding*)**

Aplicada a todas as variáveis categóricas nominais restantes para convertê-las em um formato numérico binário, utilizando `pd.get_dummies()`.

* **Função:** `pd.get_dummies(df, drop_first=False, dtype=int)`
* **Lógica:** Para cada categoria única em uma coluna, uma nova coluna binária (com valores `0` ou `1`) é criada.

| Colunas Afetadas (Exemplos) | Transformação | Exemplo de Novas Colunas Geradas |
| :--- | :--- | :--- |
| `Faixa Etária` | One-Hot Encoding | `Faixa Etária_Faixa_1_Idade`, `Faixa Etária_Faixa_2_Idade`, ... |
| `Cor/raca/etnia` | One-Hot Encoding | `Cor/raca/etnia_Amarela`, `Cor/raca/etnia_Branca`, `Cor/raca/etnia_Parda`, ... |
| `Região onde mora` | One-Hot Encoding | `Região onde mora_Centro-oeste`, `Região onde mora_Nordeste`, ... |



## 2.2. Dicionário de Dados da base modificada(pré-processada)

| Atributo | Qtde de Instâncias | Tipo do atributo |
|---|---|---|
| Genero | 5008 | Categórico |
| PCD | 5008 | Categórico |
| Área de formação em tecnologia | 5008 | Categórico |
| Situação de trabalho | 5008 | Categórico |
| Nível de Ensino | 5008 | Categórico |
| Cor/raca/etnia_Amarela | 5008 | Categórico |
| Cor/raca/etnia_Branca | 5008 | Categórico |
| Cor/raca/etnia_Indígena | 5008 | Categórico |
| Cor/raca/etnia_Outra | 5008 | Categórico |
| Cor/raca/etnia_Parda | 5008 | Categórico |
| Cor/raca/etnia_Prefiro não informar | 5008 | Categórico |
| Cor/raca/etnia_Preta | 5008 | Categórico |
| Região onde mora_Centro-oeste | 5008 | Categórico |
| Região onde mora_Nordeste | 5008 | Categórico |
| Região onde mora_Norte | 5008 | Categórico |
| Região onde mora_Sudeste | 5008 | Categórico |
| Região onde mora_Sul | 5008 | Categórico |
| Faixa Etária_Faixa_1_Idade | 5008 | Categórico |
| Faixa Etária_Faixa_2_Idade | 5008 | Categórico |
| Faixa Etária_Faixa_3_Idade | 5008 | Categórico |
| Faixa Etária_Faixa_4_Idade | 5008 | Categórico |


## 3. Análise Descritiva dos Dados utilizando Estatísticas de Primeira Ordem

* **Descrição:** Esta seção apresenta uma análise descritiva das colunas da base de dados processada (`base_princ`), utilizando estatísticas de primeira ordem para descrever a distribuição e as características dos dados.

## Descrição de Dados Numéricos

As colunas na base de dados processada foram convertidas para o tipo `int` após a codificação das variáveis categóricas. Embora representem categorias, sua análise estatística descritiva pode fornecer insights sobre a distribuição dos valores codificados. A coluna 'Idade' é a única numérica original antes do processamento extenso das demais colunas.

Para dados numéricos, as estatísticas de primeira ordem incluem:

* **Média:** Medida de tendência central.
* **Mediana:** Valor central dos dados ordenados.
* **Moda:** Valor mais frequente nos dados.
* **Desvio Padrão:** Medida de dispersão dos dados em torno da média.
* **Variância:** Quadrado do desvio padrão, outra medida de dispersão.
* **Mínimo e Máximo:** Limites inferior e superior dos dados.
* **Quartis:** Valores que dividem os dados em quatro partes iguais (25%, 50% - mediana, 75%).

Considerando a saída do seu código para a análise estatística, podemos descrever cada coluna:

### Análise da Coluna 'Idade'

* **Média:** 31.96 anos.
* **Mediana:** 30.00 anos.
* **Moda:** 27.00 anos (o valor mais frequente de idade).
* **Desvio Padrão:** 7.55 anos (indica a dispersão das idades em torno da média).
* **Mínimo:** 18.00 anos.
* **Máximo:** 73.00 anos.
* **Quartis:** 25% dos respondentes têm 27 anos ou menos, 50% têm 30 anos ou menos, e 75% têm 36 anos ou menos.

### Análise da Coluna 'Genero'

* **Média:** 0.25 (considerando a codificação, indica a proporção relativa entre os gêneros).
* **Mediana:** 0.00.
* **Moda:** 1.00 (o gênero com maior frequência na codificação).
* **Desvio Padrão:** 0.43.
* **Mínimo:** 0.00.
* **Máximo:** 1.00.
* **Quartis:** 75% dos valores codificados de gênero são 0.

### Análise da Coluna 'Cor/raca/etnia'

* **Média:** 0.91 (valor médio da codificação da cor/raça/etnia).
* **Mediana:** 0.00.
* **Moda:** 3.00 (a cor/raça/etnia com maior frequência na codificação).
* **Desvio Padrão:** 1.34.
* **Mínimo:** 0.00.
* **Máximo:** 6.00.
* **Quartis:** 75% dos valores codificados de cor/raça/etnia são 3 ou menos.

### Análise da Coluna 'PCD'

* **Média:** 0.02 (indica a proporção de respondentes que se identificam como PCD na codificação).
* **Mediana:** 0.00.
* **Moda:** 1.00 (a categoria de PCD com maior frequência na codificação).
* **Desvio Padrão:** 0.14.
* **Mínimo:** 0.00.
* **Máximo:** 1.00.
* **Quartis:** 75% dos valores codificados para PCD são 0.


### Análise da Coluna 'Regiao onde mora'

* **Média:** 2.17 (valor médio da codificação da região).
* **Mediana:** 2.00.
* **Moda:** 2.00 (a região com maior frequência na codificação).
* **Desvio Padrão:** 0.77.
* **Mínimo:** 0.00.
* **Máximo:** 4.00.
* **Quartis:** 75% dos respondentes moram em regiões codificadas como 3 ou menos.

### Análise da Coluna 'Nível de Ensino'

* **Média:** 2.59 (valor médio da codificação do nível de ensino).
* **Mediana:** 3.00.
* **Moda:** 3.00 (o nível de ensino com maior frequência na codificação).
* **Desvio Padrão:** 1.00.
* **Mínimo:** 1.00.
* **Máximo:** 5.00.
* **Quartis:** 75% dos respondentes têm nível de ensino codificado como 3 ou menos.

### Análise da Coluna 'Área de formação'

* **Média:** 1.32 (valor médio da codificação da área de formação).
* **Mediana:** 1.00.
* **Moda:** 2.00 (a área de formação com maior frequência na codificação).
* **Desvio Padrão:** 1.72.
* **Mínimo:** 0.00.
* **Máximo:** 7.00.
* **Quartis:** 75% dos respondentes têm área de formação codificada como 2 ou menos.

### Análise da Coluna 'Situação de trabalho'

* **Média:** 0.09 (indica a proporção de respondentes em uma das categorias de situação de trabalho na codificação).
* **Mediana:** 0.00.
* **Moda:** 1.00 (a situação de trabalho com maior frequência na codificação).
* **Desvio Padrão:** 0.28.
* **Mínimo:** 0.00.
* **Máximo:** 1.00.
* **Quartis:** 75% dos valores codificados para situação de trabalho são 0.

**Observação:** É crucial lembrar que a interpretação dessas estatísticas para as colunas codificadas deve ser feita com cautela, pois os números representam categorias e não possuem uma escala numérica inerente. A análise é mais útil para entender a distribuição dos códigos dentro de cada coluna. Para a coluna 'Idade', a interpretação é direta, pois se trata de uma variável numérica contínua.




## Indução de modelos

### Modelo 1: Árvore de Decisão

# Análise de Projeto de Classificação com Árvore de Decisão

Com base na análise do código Python fornecido, apresento uma descrição detalhada do projeto de classificação, abordando a escolha do modelo, o processo de amostragem, os parâmetros utilizados e os trechos de código mais relevantes.

## Justificativa da Escolha do Modelo

O modelo escolhido para este problema de classificação foi a **Árvore de Decisão (`DecisionTreeClassifier`)**. Essa escolha é justificada por várias razões:

* **Interpretabilidade**: As árvores de decisão são modelos de "caixa branca". Isso significa que a lógica por trás de suas previsões é fácil de entender e visualizar. Como o código demonstra ao final, é possível plotar a árvore inteira e seguir o caminho das decisões com base nas características (features) dos dados, tornando o resultado transparente.
* **Tratamento de Dados Não-Lineares**: O modelo pode capturar relações não-lineares complexas entre as features e o alvo, sem a necessidade de transformações complexas dos dados de entrada.
* **Requisitos Mínimos de Pré-processamento**: Árvores de decisão não exigem a normalização ou padronização dos dados numéricos, o que simplifica a fase de preparação.
* **Base para Modelos Mais Complexos**: A Árvore de Decisão é o bloco de construção fundamental para algoritmos mais robustos como `Random Forest` e `Gradient Boosting`, tornando-a um excelente ponto de partida para um projeto de classificação.

## Processo de Amostragem de Dados

O tratamento e a amostragem dos dados foram realizados de forma robusta para garantir que o modelo seja treinado e avaliado corretamente, evitando problemas comuns como superestimação de performance (*overfitting*) e vazamento de dados (*data leakage*).

### 1. Particionamento em Treino e Teste

Inicialmente, o conjunto de dados foi dividido em dois subconjuntos: um para treino (85%) e outro para teste (15%). Foi utilizada a função `train_test_split`.

* **Estratificação (`stratify=y`)**: A estratificação foi usada para garantir que a proporção das classes (ex: "Empregado" e "Desempregado") fosse a mesma tanto no conjunto de treino quanto no de teste. Isso é crucial em cenários com classes desbalanceadas, pois evita que um dos conjuntos tenha uma representação muito diferente do outro.
* **Reprodutibilidade (`random_state=42`)**: A definição de um `random_state` garante que a divisão dos dados seja sempre a mesma em todas as execuções do código, permitindo a reprodutibilidade dos resultados.
```python
# -*- coding: utf-8 -*-
# Separação da variável alvo (y) e das features (X)
y = df['Situação de trabalho']
X = df.drop('Situação de trabalho', axis=1)

# Divisão dos dados em treino e teste
# test_size=0.15 define que 15% dos dados serão para teste
# stratify=y garante a proporção das classes nos dois conjuntos
# random_state=42 garante a reprodutibilidade da divisão
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, stratify=y, random_state=42
)
```
### 2. Validação Cruzada (Cross-Validation)

Para o ajuste de hiperparâmetros e avaliação do modelo, foi utilizada a **Validação Cruzada com 5 folds (`cv=5`)**. Este método divide o conjunto de treinamento em 5 partes (folds). O modelo é treinado 5 vezes, usando 4 folds para treino e 1 para validação em cada iteração. A performance final é a média dos resultados das 5 iterações.

Isso proporciona uma estimativa mais estável e confiável da performance do modelo, reduzindo o risco de que o resultado seja apenas uma coincidência de uma única divisão de dados.

### 3. Balanceamento de Classes com SMOTE dentro de um Pipeline

O código identifica um potencial desbalanceamento de classes e utiliza a técnica **SMOTE (Synthetic Minority Over-sampling Technique)** para lidar com isso. O SMOTE cria novas amostras sintéticas da classe minoritária, balanceando o conjunto de dados de treinamento.

Para evitar o **vazamento de dados**, onde informações do conjunto de validação "vazam" para o treinamento, o SMOTE foi aplicado corretamente dentro de um **Pipeline**. O `Pipeline` garante que o SMOTE seja aplicado apenas nos dados de treinamento de cada fold da validação cruzada. O conjunto de validação (e o conjunto de teste final) permanece inalterado, simulando um ambiente real.

O código inclui uma ferramenta de verificação **(`DataChecker`)** para provar que o SMOTE está sendo aplicado corretamente dentro do fluxo.

```python
# -*- coding: utf-8 -*-
# Criação do Pipeline para o GridSearch
# O Pipeline encadeia os passos de pré-processamento e o modelo
pipeline_for_grid = Pipeline([
    # 1º Passo: Aplica o SMOTE para balancear as classes (apenas nos dados de treino de cada fold)
    ('smote', SMOTE(random_state=42)),
    # Passo de verificação para confirmar a aplicação do SMOTE
    ('data_checker', DataChecker()),
    # 2º Passo: Treina o modelo de Árvore de Decisão
    ('rf', DecisionTreeClassifier(random_state=42))
])

# Definição do GridSearchCV com o pipeline
# cv=5 indica a validação cruzada de 5 folds
grid_search = GridSearchCV(
    estimator=pipeline_for_grid,
    param_grid=param_grid,
    cv=5,
    scoring='precision',
    n_jobs=-1,
    verbose=2
)

# O grid_search.fit aplica o pipeline (com SMOTE) e a validação cruzada
grid_search.fit(X_train, y_train)
```

### Descrição dos Parâmetros Utilizados
A otimização do modelo foi realizada com GridSearchCV, que testa sistematicamente uma combinação de diferentes hiperparâmetros para encontrar a melhor configuração.

**Parâmetros da Árvore de Decisão (DecisionTreeClassifier)**

Os seguintes hiperparâmetros do modelo foram otimizados:

* **max_depth:** Controla a profundidade máxima da árvore. Os valores testados foram [None, 10, 20]. None permite que a árvore cresça até que todas as folhas sejam puras. Limitar a profundidade ajuda a prevenir o overfitting.
 
* **min_samples_split:** Define o número mínimo de amostras necessárias para dividir um nó interno. Os valores testados foram [2, 5]. Valores maiores podem prevenir a criação de divisões que se baseiam em poucas amostras, tornando o modelo mais geral.
  
* **min_samples_leaf:** Define o número mínimo de amostras que uma folha (um nó terminal) deve ter. Os valores testados foram [1, 2]. Assim como o min_samples_split, este parâmetro ajuda a suavizar o modelo e evitar o overfitting.


```python
# -*- coding: utf-8 -*-
# Definição da grade de parâmetros a ser testada
# A notação 'rf__<parametro>' informa ao GridSearchCV para aplicar
# o parâmetro ao passo nomeado 'rf' no pipeline.
param_grid = {
    'rf__max_depth': [None, 10, 20],
    'rf__min_samples_split': [2, 5],
    'rf__min_samples_leaf': [1, 2]
}

```

**Parâmetros do GridSearchCV**
* **estimator:** O objeto que será otimizado, que neste caso é o pipeline_for_grid.
* **param_grid:** O dicionário com os hiperparâmetros a serem testados.
* **cv:** O número de folds para a validação cruzada (definido como 5).
* **scoring:** A métrica usada para avaliar qual combinação de parâmetros é a melhor. Foi escolhida a precision (precisão). Isso sugere que o objetivo principal do modelo é minimizar os falsos positivos (ou seja, quando o modelo prevê "Desempregado(a)", ele deve estar muito certo disso).
* **n_jobs=-1:** Utiliza todos os processadores disponíveis para paralelizar a busca, acelerando o processo.
 
### Fluxo de Processamento e Visualizações
O código gera várias visualizações para diagnosticar, avaliar e interpretar o modelo.

**1. Curva de Aprendizagem:** Este gráfico (gerado no início) ajuda a diagnosticar se o modelo sofre de alto viés (underfitting) ou alta variância (overfitting). Ele plota a performance do modelo nos dados de treino e de validação cruzada à medida que o número de amostras de treinamento aumenta.


* **Resultado esperado:** Idealmente, as duas curvas (treino e validação) convergem para um score alto. Se a curva de validação permanece baixa enquanto a de treino é alta, há overfitting.
 
**2. Curva de Precisão-Recall vs. Limiar de Decisão:** Modelos de classificação retornam probabilidades. O limiar de decisão (padrão 0.5) converte essa probabilidade em uma classe (0 ou 1). Este gráfico permite escolher um limiar otimizado. No código, ele é gerado para ambas as classes, mostrando como a precisão e o recall de cada uma mudam conforme o limiar varia. Isso é fundamental para ajustar o comportamento do modelo às necessidades do negócio (por exemplo, aumentar o recall da classe "Desempregado" mesmo que a precisão diminua um pouco).


**3. Matrizes de Confusão:** Apresentam um resumo visual da performance do modelo. Elas mostram os verdadeiros positivos, verdadeiros negativos, falsos positivos e falsos negativos. O código gera matrizes para os conjuntos de treino e teste, permitindo comparar a performance e verificar se há overfitting.


```python
# -*- coding: utf-8 -*-
# Matriz de Confusão do Teste com o novo limiar
print("\nMatriz de Confusão Final:")
cm = confusion_matrix(y_test, y_pred_novo_limiar)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Previsto")
plt.ylabel("Real")
plt.title(f"Matriz de Confusão com Limiar = {novo_limiar}")
plt.show()
```


**Visualização da Árvore de Decisão:** Esta é a principal vantagem do modelo. O código plota a estrutura completa da árvore final, mostrando as regras de decisão em cada nó, o número de amostras e a distribuição das classes.


* **Como ler:** A partir do nó raiz (topo), cada nó faz uma pergunta sobre uma feature. Se a condição for verdadeira, segue-se para um lado; se for falsa, para o outro. O processo continua até chegar a uma folha, que determina a previsão da classe.
**Importância das Features:** Este gráfico de barras mostra quais características (features) foram mais importantes para o modelo tomar suas decisões. A importância é calculada com base em quanto cada feature contribui para reduzir a impureza nos nós da árvore. Isso ajuda a entender quais variáveis são mais preditivas para determinar a situação de trabalho de um indivíduo.
```python
# -*- coding: utf-8 -*-
# Acessar o passo do modelo de Árvore de Decisão DENTRO do pipeline
rf_step = final_model.named_steps['rf']
importances = rf_step.feature_importances_

# Criar um DataFrame para visualização
feature_importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': importances})
top_20_features = feature_importance_df.sort_values(by='Importance', ascending=False).head(20)

# Gerar o gráfico de barras
plt.figure(figsize=(12, 10))
sns.barplot(x='Importance', y='Feature', data=top_20_features, palette='viridis')
plt.title('Top 20 Features Mais Importantes (Modelo Otimizado via Pipeline)', fontsize=18)
plt.xlabel('Importância', fontsize=14)
plt.ylabel('Feature', fontsize=14)
plt.tight_layout()
plt.show()
```




# Resultados obtidos com o modelo 1 (Árvore de decisão).
Observação: Fiz duas avaliações utilizando métricas diferentes, com isso obtive diferentes resultados:
Primeira métrica eu obtive uma maior acurácia e precisão e recall em ambas as classes(Empregado(a) e Desempregado(a)). Porém percebi que o modelo estava priorizando mais a classe majoritária(Empregado(a)), por haver cerca de 10 vezes mais dados em relação a outra. Segue as duas avaliações...

## Avaliação 01:


![2d52dec8-827e-4dae-8efe-1e85e52eb25d](https://github.com/user-attachments/assets/d2c22032-1f0a-4085-ad8f-1cecb2c0da41)

![image](https://github.com/user-attachments/assets/1be4f89d-eb49-439d-a813-07189919b766)

## Acurácia do Modelo Inicial:

`0.9115537848605577`

## Relatório de Classificação do Modelo Inicial:

|               | precision | recall | f1-score | support |
|---------------|-----------|--------|----------|---------|
| 0             | 0.91      | 1.00   | 0.95     | 1146    |
| 1             | 0.33      | 0.02   | 0.03     | 109     |
| **accuracy** |           |        | **0.91** | **1255**|
| **macro avg** | 0.62      | 0.51   | 0.49     | 1255    |
| **weighted avg**| 0.86      | 0.91   | 0.87     | 1255    |

## Acurácia nos Conjuntos de Treino e Teste:

* **Acurácia de treino:** `0.9133`
* **Acurácia de teste:** `0.9116`


## Avaliação 02:

Utilizei muitos hiperparâmetros para tentar balancear os dados e fornecer uma maior importância para a classe minoritária, tendo como resultado um maior balanceameno dos dados. porém o resultado(acurácia) diminuiu significadamente, e a classificação preditiva de meus dados não foram satisfatórias. Nesse quesito, utilizei LLM para me sugerir mudanças, e por fim, elas me sugeriram testar com um novo modelo, como a Random Forest, o qual foi utilizado no modelo 2.

![download](https://github.com/user-attachments/assets/103ff659-4ef6-4e01-89d5-78b794261d50)

![download](https://github.com/user-attachments/assets/7634ae46-a069-44f1-be2a-9fdd646e07ba)

## --- Abordagem: Ajuste de Hiperparâmetros com GridSearchCV ---

**Melhores hiperparâmetros encontrados (foco na classe 1):**
{'class_weight': {0: 1, 1: 10}, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 5, 'min_samples_split': 5}


**Acurácia do melhor modelo (GridSearchCV - Treino):** `0.7102604997341839`

**Acurácia do melhor modelo (GridSearchCV - Teste):** `0.6772908366533864`

**Avaliação do melhor modelo (GridSearchCV - foco na classe 1):**
Acurácia: 0.6772908366533864


**Relatório de Classificação:**

|               | precision | recall | f1-score | support |
|---------------|-----------|--------|----------|---------|
| 0             | 0.93      | 0.70   | 0.80     | 1146    |
| 1             | 0.13      | 0.47   | 0.20     | 109     |
| **accuracy** |           |        | **0.68** | **1255**|
| **macro avg** | 0.53      | 0.58   | 0.50     | 1255    |
| **weighted avg**| 0.86      | 0.68   | 0.75     | 1255    |

Ao otimizar o modelo com o f1_score ponderado para a classe 1 no GridSearchCV, você estava explicitamente instruindo o algoritmo a encontrar parâmetros que equilibrassem a precisão e o recall da classe "Desempregadas", dando maior peso à capacidade do modelo de identificar todas as instâncias dessa classe. Os resultados mostram que, embora o recall da classe 1 tenha melhorado em relação a um modelo puramente focado na acurácia geral, ainda há um trade-off com a precisão dessa classe.


### Interpretação do modelo 1

![download](https://github.com/user-attachments/assets/88f497c9-c5ba-416b-8707-017f70fd520d)

## Importância das Features na Árvore de Decisão

**Idade: A Feature Mais Importante**

O fato de "Idade" estar em primeiro lugar significa que, de todas as features consideradas pelo modelo, a idade da pessoa é a informação que mais impacta a decisão do modelo sobre a `Situação de trabalho`. O modelo encontra na idade padrões muito fortes que o ajudam a separar as diferentes classes da variável alvo. Isso sugere que há uma relação significativa entre a faixa etária e a situação de trabalho no seu conjunto de dados.

**Nível de Ensino: A Segunda Feature Mais Importante**

"Nível de Ensino" é a segunda feature mais importante. Isso indica que a escolaridade da pessoa também é uma informação crucial para o modelo. A Árvore de Decisão provavelmente usa o nível de ensino para criar divisões importantes nos seus nós, mostrando que o grau de instrução tem um forte poder preditivo sobre a situação de trabalho.

**Região onde mora e Gênero: Importância Moderada**

"Região onde mora" e "Gênero" aparecem depois de "Idade" e "Nível de Ensino". Isso sugere que, embora sejam importantes, a influência deles nas decisões do modelo é menor do que a idade e o nível de ensino. O modelo provavelmente utiliza essas informações para refinar as suas previsões dentro dos grupos já definidos pela idade e escolaridade.

**UF, Cor/Raça/Etnia e Área de Formação: Features Menos Importantes**

"UF", "Cor/Raça/Etnia" e "Área de Formação" são as features menos importantes na lista que você forneceu. Isso não significa que elas não tenham nenhuma importância, mas sim que, no contexto deste modelo específico e deste conjunto de dados, elas contribuíram menos para as decisões finais do que as features no topo da lista. A "Área de Formação" ser a menos importante pode indicar que, para este problema específico e a forma como os dados estão representados, essa informação não é tão discriminatória quanto as outras para determinar a situação de trabalho.

**Em Resumo:**

Seu modelo de Árvore de Decisão considera a **idade** e o **nível de ensino** como os fatores mais determinantes para prever a situação de trabalho. Features demográficas como **região**, **gênero**, **UF**, **cor/raça/etnia** e **área de formação** também são consideradas, mas com menor peso na tomada de decisão do modelo.

![download](https://github.com/user-attachments/assets/b2e4b1b2-1df8-433b-b063-b03ba1ed065b)



# Resultados obtidos com o modelo 2 (Random Forest).


### Avaliação 01:

![download](https://github.com/user-attachments/assets/5c253440-4bf8-465d-859e-fbb9ff592562)

## Melhores Parâmetros Encontrados:

{'class_weight': 'balanced', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}


## Melhor Pontuação (F1-macro) Obtida:

`0.7106123941935574`

## Acurácia de treino: 
0.7817
## Acurácia de teste: 
0.7458

## Relatório de Classificação com Melhores Parâmetros no Conjunto de Teste:

|               | precision | recall | f1-score | support |
|---------------|-----------|--------|----------|---------|
| 0             | 0.93      | 0.78   | 0.85     | 1144    |
| 1             | 0.16      | 0.42   | 0.23     | 111     |
| **accuracy** |           |        | **0.75** | **1255**|
| **macro avg** | 0.54      | 0.60   | 0.54     | 1255    |
| **weighted avg**| 0.86      | 0.75   | 0.79     | 1255    |

### Avaliação 02:
Utilizei novos parâmetros para análise, tentei equilibrar os resultados das classes, porém não consegui ter um valor satisfatório no recall e na precisão.

![download](https://github.com/user-attachments/assets/5ab5f6c2-d17d-4685-879f-133a05abb3b5)

## Avaliação com Limiar de Decisão de 0.5:

**Limiar:** `0.5`
* **Recall classe 0:** `0.76`
* **Precision classe 0:** `0.93`
* **F1-score classe 0:** `0.84`

**Matriz de Confusão (Limiar 0.5):**

[[871 273]
[ 63  48]]


**Relatório de Classificação (Limiar 0.5):**

|               | precision | recall | f1-score | support |
|---------------|-----------|--------|----------|---------|
| 0             | 0.93      | 0.76   | 0.84     | 1144    |
| 1             | 0.15      | 0.43   | 0.22     | 111     |
| **accuracy** |           |        | **0.73** | **1255**|
| **macro avg** | 0.54      | 0.60   | 0.53     | 1255    |
| **weighted avg**| 0.86      | 0.73   | 0.78     | 1255    |

Repita o passo anterior com os resultados do modelo 2.





### Interpretação do modelo 2

![download](https://github.com/user-attachments/assets/30568082-b86e-4478-acda-920538c83799)

1-UF (Unidade Federativa): A variável mais importante, indicando que o estado de residência é o fator mais preditivo da situação de trabalho.

2-Nível de Ensino: A segunda variável mais importante. O nível de escolaridade de uma pessoa tem uma forte influência na sua situação de trabalho.

3-Área de formação: A área de formação é o terceiro fator mais importante, sugerindo que a área de estudo ou profissão também é um preditor relevante.

4-Regiao onde mora: A região geográfica de residência tem uma influência menor que as três primeiras.

5-Cor/raca/etnia: A cor, raça ou etnia apresenta uma importância ainda menor, mas não desprezível.

6-Genero: O gênero é a variável com a menor importância relativa para o modelo.


![download](https://github.com/user-attachments/assets/914d4929-d532-4b1c-98c6-895b7556a551)

Recall Alto com Limiar Pequeno:

Isso significa que quando você define um limiar baixo, o modelo tende a classificar mais observações como pertencentes à classe positiva (a classe que você está tentando prever com maior sensibilidade).
Em outras palavras, o modelo está capturando uma grande proporção de todas as instâncias reais da classe positiva.
A consequência é que você está incluindo mais verdadeiros positivos, mas também mais falsos positivos.

Precisão e F1-score Baixos com Limiar Pequeno:

A precisão baixa indica que, embora o modelo esteja encontrando muitos dos casos reais da classe positiva, ele também está classificando incorretamente muitas observações negativas como positivas.
Há muitos falsos positivos, o que diminui a confiabilidade das previsões positivas.
O F1-score baixo é uma consequência direta da baixa precisão, pois o F1-score é a média harmônica entre precisão e recall.

Encontro dos Scores Próximo ao Limiar 0.8:

O ponto onde a precisão, o recall e o F1-score se aproximam geralmente indica um ponto de equilíbrio.
Nesse limiar, o modelo está encontrando um melhor compromisso entre classificar corretamente a maioria dos casos positivos e evitar falsos positivos.
Esse limiar pode ser considerado um ponto "ótimo" para este modelo e conjunto de dados.

O Que Isso Quer Dizer na Prática?

Trade-off: Seu gráfico ilustra claramente o trade-off entre precisão e recall.
Se você precisa capturar o máximo possível de casos positivos (alto recall), você terá que aceitar uma precisão mais baixa.
Se você precisa ter alta confiança em suas previsões positivas (alta precisão), você pode perder alguns casos positivos.
Desbalanceamento: A situação descrita sugere que seus dados podem estar desbalanceados, com uma classe sendo muito mais frequente que a outra. Modelos tendem a ter mais dificuldade em prever a classe minoritária.

Aplicação: A escolha do limiar depende do contexto da sua aplicação.
Se o custo de um falso negativo for alto, você pode preferir um limiar mais baixo para maximizar o recall.
Se o custo de um falso positivo for alto, você pode preferir um limiar mais alto para maximizar a precisão.

Exemplo:

Imagine que você está tentando prever se pacientes têm uma doença rara.

Se você usar um limiar baixo, você identificará a maioria dos pacientes doentes (alto recall), mas também classificará erroneamente muitos pacientes saudáveis como doentes (baixa precisão). Isso pode levar a mais testes e ansiedade desnecessários.
Se você usar um limiar alto, você terá alta confiança de que os pacientes que você identifica como doentes realmente têm a doença, mas você pode perder alguns pacientes doentes que precisam de tratamento.
No seu caso, a classe "Desempregado" é geralmente a classe minoritária. Se for muito importante identificar o máximo de pessoas desempregadas para oferecer ajuda, você pode trabalhar com um limiar mais baixo, mesmo que isso signifique que algumas pessoas empregadas sejam classificadas como desempregadas.


## Análise comparativa dos modelos

## Comparativo entre Árvore de Decisão e Random Forest

Com base nas métricas e informações fornecidas, podemos comparar as forças e fragilidades dos modelos de Árvore de Decisão e Random Forest para a sua tarefa de prever a situação de trabalho.

**Árvore de Decisão:**

* **Acurácia (Teste):** 0.68
* **Precisão (Classe 0 - Empregado):** 0.93
* **Precisão (Classe 1 - Desempregado):** 0.13
* **Recall (Classe 0 - Empregado):** 0.70
* **Recall (Classe 1 - Desempregado):** 0.47
* **F1-Score (Classe 0 - Empregado):** 0.80
* **F1-Score (Classe 1 - Desempregado):** 0.20
* **Interpretabilidade:** Alta. A estrutura da árvore pode ser visualizada e as decisões são facilmente rastreáveis através dos nós e regras.
* **Importância das Features:** Idade > Nível de Ensino > Região onde mora > Gênero > UF > Cor/Raça/Etnia > Área de Formação (conforme sua análise anterior).

**Random Forest:**

* **Acurácia (Teste):** 0.73 (com limiar de 0.5)
* **Precisão (Classe 0 - Empregado):** 0.93
* **Precisão (Classe 1 - Desempregado):** 0.15
* **Recall (Classe 0 - Empregado):** 0.76
* **Recall (Classe 1 - Desempregado):** 0.43
* **F1-Score (Classe 0 - Empregado):** 0.84
* **F1-Score (Classe 1 - Desempregado):** 0.22
* **Interpretabilidade:** Baixa. O modelo é um conjunto de muitas árvores, tornando a interpretação das decisões individuais complexa. A importância das features pode ser avaliada, mas o caminho decisório para uma única previsão não é tão claro.
* **Importância das Features:** UF > Nível de Ensino > Área de formação > Região onde mora > Cor/raca/etnia > Genero (conforme sua análise anterior da Random Forest).

**Forças e Fragilidades:**

| Característica        | Árvore de Decisão                                     | Random Forest                                                |
| :-------------------- | :---------------------------------------------------- | :----------------------------------------------------------- |
| **Acurácia** | Menor (0.68)                                          | Maior (0.73)                                                 |
| **Precisão (Classe 0)** | Similar (0.93)                                        | Similar (0.93)                                               |
| **Precisão (Classe 1)** | Menor (0.13)                                          | Maior (0.15)                                                 |
| **Recall (Classe 0)** | Menor (0.70)                                          | Maior (0.76)                                                 |
| **Recall (Classe 1)** | Maior (0.47)                                          | Menor (0.43)                                                 |
| **F1-Score (Classe 0)** | Menor (0.80)                                          | Maior (0.84)                                                 |
| **F1-Score (Classe 1)** | Menor (0.20)                                          | Maior (0.22)                                                 |
| **Interpretabilidade** | Alta                                                  | Baixa                                                        |
| **Robustez a Overfitting** | Mais suscetível, especialmente árvores profundas      | Menos suscetível devido à agregação de múltiplas árvores      |
| **Lida com Não Linearidades** | Bem                                                   | Bem                                                          |
| **Estabilidade** | Pequenas variações nos dados podem mudar a estrutura | Mais estável, menos sensível a pequenas variações nos dados |

**Casos em que um modelo se sairia melhor que o outro:**

* **Cenário 1: Necessidade de Interpretabilidade para Ações Diretas**
    * **Melhor Modelo:** Árvore de Decisão.
    * **Exemplo:** Imagine que você precisa entender exatamente quais regras levam à previsão de desemprego para criar políticas públicas direcionadas. Uma árvore de decisão, com sua estrutura clara de regras "SE...ENTÃO...", pode fornecer insights diretos sobre combinações de idade, nível de ensino e região que estão fortemente associadas ao desemprego. Você pode visualizar o caminho que leva a essa previsão e identificar grupos específicos para intervenção. A interpretabilidade aqui é mais valiosa do que um pequeno ganho em acurácia.

* **Cenário 2: Previsão com Foco na Robustez e Generalização em Dados Complexos**
    * **Melhor Modelo:** Random Forest.
    * **Exemplo:** Considere um cenário onde os fatores que influenciam a situação de trabalho são altamente não lineares e interagem de maneiras complexas (por exemplo, combinações sutis de área de formação, experiência profissional não capturada diretamente e fatores econômicos regionais). O Random Forest, ao agregar as decisões de muitas árvores treinadas em diferentes subconjuntos dos dados e features, tende a ser mais robusto a essas complexidades e generaliza melhor para novos dados não vistos durante o treinamento. Mesmo que você não consiga interpretar o caminho de cada previsão, a maior acurácia e a menor chance de overfitting podem ser cruciais para uma ferramenta de previsão em larga escala.

* **Cenário 3: Desbalanceamento Extremo da Classe Alvo**
    * **Consideração:** Ambos os modelos podem ter dificuldades com desbalanceamento extremo. No entanto, o Random Forest, com seus mecanismos de amostragem e a possibilidade de ajuste de `class_weight`, pode ser mais flexível para lidar com isso, especialmente se o foco for em métricas como F1-score para a classe minoritária. A Árvore de Decisão pode se tornar enviesada para a classe majoritária mais facilmente.
    * **Exemplo:** Se a taxa de desemprego na sua amostra fosse extremamente baixa (por exemplo, apenas 5%), o Random Forest, com a sua capacidade de explorar diferentes subespaços de features e amostras, poderia capturar melhor os padrões da classe minoritária se bem ajustado.

* **Cenário 4: Necessidade de Previsões Rápidas em Tempo Real**
    * **Consideração:** Árvores de Decisão geralmente são mais rápidas para prever uma vez treinadas, pois envolvem percorrer uma única árvore. Random Forests exigem a agregação das previsões de muitas árvores, o que pode ser mais computacionalmente intensivo durante a previsão.
    * **Exemplo:** Se você precisasse de um sistema de previsão em tempo real com baixíssima latência para classificar rapidamente candidatos a empregos ou pessoas em busca de assistência, uma Árvore de Decisão bem otimizada poderia ser preferível devido à sua velocidade de previsão.

**Conclusão:**

Ambos os modelos têm seus méritos e desvantagens. A escolha do melhor modelo depende fortemente dos seus objetivos específicos, da natureza dos seus dados e das prioridades do seu projeto (interpretabilidade, acurácia, robustez, velocidade). O Random Forest geralmente oferece melhor desempenho preditivo e robustez, enquanto a Árvore de Decisão brilha na interpretabilidade. Analisar as métricas detalhadas para a classe minoritária (desempregado) e considerar o custo de falsos positivos e falsos negativos em seu contexto específico ajudará a tomar a decisão mais informada.

### Distribuição do modelo (opcional)

Tende criar um pacote de distribuição para o modelo construído, para ser aplicado 
em um sistema inteligente.


## 8. Conclusão

Apresente aqui a conclusão do seu trabalho. Discussão dos resultados obtidos no trabalho, 
onde se verifica as observações pessoais de cada aluno.

Uma conclusão deve ter 3 partes:

   * Breve resumo do que foi desenvolvido
	 * Apresenação geral dos resultados obtidos com discussão das vantagens e desvantagens do sistema inteligente
	 * Limitações e possibilidades de melhoria


# REFERÊNCIAS

Como um projeto de sistema inteligente não requer revisão bibliográfica, 
a inclusão das referências não é obrigatória. No entanto, caso você 
tenha utilizado referências na introdução ou deseje 
incluir referências relacionadas às tecnologias, padrões, ou metodologias 
que serão usadas no seu trabalho, relacione-as de acordo com a ABNT.

Verifique no link abaixo como devem ser as referências no padrão ABNT:

http://www.pucminas.br/imagedb/documento/DOC\_DSC\_NOME\_ARQUI20160217102425.pdf

Por exemplo:

**[1]** - _ELMASRI, Ramez; NAVATHE, Sham. **Sistemas de banco de dados**. 7. ed. São Paulo: Pearson, c2019. E-book. ISBN 9788543025001._

**[2]** - _COPPIN, Ben. **Inteligência artificial**. Rio de Janeiro, RJ: LTC, c2010. E-book. ISBN 978-85-216-2936-8._

**[3]** - _CORMEN, Thomas H. et al. **Algoritmos: teoria e prática**. Rio de Janeiro, RJ: Elsevier, Campus, c2012. xvi, 926 p. ISBN 9788535236996._

**[4]** - _SUTHERLAND, Jeffrey Victor. **Scrum: a arte de fazer o dobro do trabalho na metade do tempo**. 2. ed. rev. São Paulo, SP: Leya, 2016. 236, [4] p. ISBN 9788544104514._

**[5]** - _RUSSELL, Stuart J.; NORVIG, Peter. **Inteligência artificial**. Rio de Janeiro: Elsevier, c2013. xxi, 988 p. ISBN 9788535237016._



# APÊNDICES

**Colocar link:**

Do código (armazenado no repositório);

Dos artefatos (armazenado do repositório);

Da apresentação final (armazenado no repositório);

Do vídeo de apresentação (armazenado no repositório).
